version: "3.9"
networks:
  caddy:
    external: false

services:
  express_app:
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=8001
    networks:
      - caddy
    depends_on:
      - caddy
      - db
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - caddy
    profiles:
      - dev
