version: "3.9"
networks:
  caddy:
    name: cadd
services:
  caddy:
    image: caddy:2.4.5-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    profiles:
      - ["prod"]
  backend:
    image: node:18-alpine

volumes:
  db-data: {}
